### ISSUE TITLE
sacPoleZeroWriter & responseWriter write identical response files when instrument changes

### ISSUE THREAD

**Issue by seisman** [crotwell/sod#1]
A minimal recipe to reproduce the bug:
```xml
<?xml version="1.0"?>
<sod>
<networkArm>
    <fdsnStation/>
    <networkCode>IM</networkCode>
    <stationCode>NV01</stationCode>
    <channelCode>SHZ</channelCode>
    <sacPoleZeroWriter/>
    <responseWriter/>
    <printlineChannelProcess/>
</networkArm>
</sod>
```

SOD Version:
```
$ sod --version
SOD 3.2.7
```

Run the recipe:
```
$ sod -f recipe.xml 
Congratulations, valid recipe.
Channel: IM.NV01..SHZ
Channel: IM.NV01..SHZ
```
The instrument of `IM.NV01..SHZ` changes in 2011. So the recipe downloads two SAC PZ files under directory polezero. It's easy to find that the two SAC PZ files are identical. The same thing happens on RESP files.

However, based on the IRIS web service, the two SAC PZ files should be different. 

http://service.iris.edu/irisws/sacpz/1/query?net=IM&sta=NV01&loc=*&cha=SHZ&starttime=2008-01-01T00:00:00&endtime=2015-01-01T00:00:00

I think it may be a bug of SOD. I also tried another station `IU.COLA.00.BHZ`, there is NO bug like this.

**Comment by crotwell** [comment]
Fixed with https://github.com/crotwell/sod/commit/b3287b0fa800b6698c7282d103d2565a68ddc833

Will be in next version, 3.2.8, out soon.

thanks for letting me know about this.

**Comment by crotwell** [comment]
New release 3.2.8 available here:
http://www.seis.sc.edu/sod/
