### ISSUE TITLE
How to download resp from a selected DMC

### ISSUE THREAD

**Issue by wangliang1989** [crotwell/sod#7]
I want to download resp from GEOFON which supports the web service:
````
<?xml version="1.0"?>
<sod>

<networkArm>
    <fdsnStation>
        <host>geofon.gfz-potsdam.de</host>
        <networkCode>GE</networkCode>
        <channelCode>BH?</channelCode>
    </fdsnStation>
    <printlineChannelProcess/>
    <responseWriter>
        <workingDir>resp1</workingDir>
        <location>RESP.${network.code}.${station.code}.${site.code}.${channel.code}</location>
    </responseWriter>
</networkArm>
</sod>
````
but sod said:

`Service Version:
1.1.2
).  SOD will continue trying it until it recovers at which point an all clear message will be issued.  If it never recovers, email sod@seis.sc.edu with this report and we can inform the server maintainer.  If you're tired of waiting, press Ctrl-C to quit.`

**Comment by crotwell** [comment]
If you look at the full error message printed it says:

> The geofon.gfz-potsdam.de server just produced an error (edu.sc.seis.seisFile.fdsnws.FDSNWSException Code: 400 Error 400: Bad Request

> including of availability information not supported

The problem is that the service refuses to answer a request that has "includeavailablility=true". The solution is to use
```
        <includeAvailability>false</includeAvailability>
```
within the `<fdsnStation>` element. This will disable the includeavailablility query param, and the request should succeed.

**Comment by wangliang1989** [comment]
Thank you very much. It helps. You are such a nice person
