### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by wangliang1989** [crotwell/sod#9]
sod version : 3.2.10
system: Mac M1
java is installed by brew

````
$ java --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)
````
````
$ sod --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:531), pid=92885, tid=8451
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment (16.0+14) (build 16+14)
# Java VM: OpenJDK 64-Bit Server VM (16+14, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Core dump will be written. Default location: /cores/core.92885
#
# An error report file with more information is saved as:
# /Users/liang/work/ss/test/recipes/II/2019/hs_err_pid92885.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
/Users/liang/opt/sod-3.2.10/bin/sod: line 109: 92885 Abort trap: 6           $JAVA -classpath $CLASSPATH -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -Dseis.name=sod3.2.10 -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton -Dpython.path=${LIB} -Djava.awt.headless=true -Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB -Dswing.volatileImageBufferEnabled=false -Djacorb.connection.client.pending_reply_timeout=20000 -Djacorb.connection.client.idle_timeout=90000 -Djacorb.home=${SOD_HOME} -Djacorb.log.default.verbosity=2 edu.sc.seis.sod.Start "$@"
````
I have use the sod on this computer successfully many times before. However, I try to use it again today. But I got the error. I don't know what happened.

Please, help me😢

**Comment by crotwell** [comment]
This looks like a problem with your installed java, not with SOD itself. I am not sure what to suggest. Perhaps you could try to uninstall java 16 and go back to 15 with
brew install openjdk@15

Are you sure you installed java with homebrew, it looks to me like the current version is still 15:
https://formulae.brew.sh/formula/openjdk

I have openjdk@15 on an M1 and SOD is working. I have not tested with 16.

**Comment by crotwell** [comment]
Just got the same error here in another java program after updating to osx 11.4 on M1. So believe this is not SOD, but rather a general java on osx 11.4 on M1 issue. I will leave this open for now.

More info here:
https://stackoverflow.com/questions/67684430/apple-siliconm1-11-4-get-a-java-error-jdk16

https://bugs.openjdk.java.net/browse/JDK-8267235

https://github.com/Homebrew/homebrew-core/issues/77954

**Comment by wangliang1989** [comment]
Thank you for your replying
The error info from java have suggested me try `ulimit -c unlimited`, but it doesn't work. after that, the info doesn't suggest this again.
`brew install openjdk@15` doesn't work.

I agree with you: the fault is from java. Because the taup fails too.

The status of the bug is RESOLVED: https://bugs.openjdk.java.net/browse/JDK-8267235
I think the java 17 will be OK.

I have another question. I should use the brew install java or openjdk in the future?

**Comment by crotwell** [comment]
I think either is fine. I prefer brew install just because it is easier to upgrade, but I think the java installed is the same in both cases.

**Comment by wangliang1989** [comment]
> I think either is fine. I prefer brew install just because it is easier to upgrade, but I think the java installed is the same in both cases.

I know my English is break English.
Now,  the java and openjdk are both installed by brew:
![image](https://user-images.githubusercontent.com/12059719/120124365-bc41cd80-c1e6-11eb-9767-110edf469336.png)

I want to know which is better? java only, openjdk only or both.

I think it will be fine soon https://github.com/Homebrew/homebrew-core/issues/77954#issuecomment-851051344.

**Comment by crotwell** [comment]
I prefer openjdk.

**Comment by wangliang1989** [comment]
install the openjdk17 by brew can fix the issue
